name: PersonalProject
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - contourpy=1.2.0
  - cycler=0.12.1
  - expat=2.5.0
  - fonttools=4.25.0
  - freetype=2.10.4
  - gcc=13.2.0
  - gcc_impl_linux-64=13.2.0
  - gcc_linux-64=13.2.0
  - gxx=13.2.0
  - gxx_impl_linux-64=13.2.0
  - icu=73.2
  - intel-openmp=2023.1.0
  - joblib=1.3.2
  - jpeg=9e
  - kernel-headers_linux-64=2.6.32
  - kiwisolver=1.4.4
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libdeflate=1.17
  - libexpat=2.5.0
  - libffi=3.4.4
  - libgcc-devel_linux-64=13.2.0
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libhwloc=2.9.0
  - libiconv=1.17
  - libpng=1.6.37
  - libsanitizer=13.2.0
  - libsqlite=3.41.2
  - libstdcxx-devel_linux-64=13.2.0
  - libstdcxx-ng=13.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxml2=2.12.5
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - matplotlib-base=3.8.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - munkres=1.1.4
  - ncurses=6.4
  - numpy=1.26.3
  - numpy-base=1.26.3
  - openjpeg=2.4.0
  - openssl=3.2.1
  - packaging=24.0
  - pillow=10.2.0
  - pip=23.3.1
  - pyaml=23.12.0
  - pyparsing=3.0.9
  - python=3.12.0
  - python-dateutil=2.9.0
  - pyyaml=6.0.1
  - readline=8.2
  - scikit-learn=1.3.0
  - scikit-optimize=0.10.0
  - scipy=1.11.4
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - sysroot_linux-64=2.12
  - tbb=2021.8.0
  - threadpoolctl=3.3.0
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.41.2
  - xz=5.4.5
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
